### ISSUE TITLE
Additional functions

### ISSUE THREAD

**Issue by anton-moskalenko** [anton-moskalenko/nexus#2]
### Tasks

- [x] Add the rest of types
- [x] Change time to GMT

### Additional

- [x] Remove unneeded domains
